SPK_NAME = tinc
SPK_VERS = 0.1.19
SPK_REV = 1
SPK_ICON = 
DSM_UI_DIR = app

DEPENDS = cross/busybox cross/$(SPK_NAME)

MAINTAINER = Cor
DESCRIPTION = tinc
DESCRIPTION_FRE = 
DESCRIPTION_SPN = 
RELOAD_UI = no
DISPLAY_NAME = Tinc

HOMEPAGE = http://www.tinc-vpn.org
LICENSE  =

WIZARDS_DIR =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh
ADDITIONAL_SCRIPTS =

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

POST_STRIP_TARGET = 

include ../../mk/spksrc.spk.mk

.PHONY: 
